### ISSUE TITLE
only tcp transport ?

### ISSUE THREAD

**Issue by atian25** [sidorares/node-adbhost#3]
so to use this, we need to install `adb.exe` and run `adb tcpip 5555` first?

**Comment by sidorares** [comment]
no, you need to enable tcp on the device, this client would talk directly to adb daemon on device

**Comment by sidorares** [comment]
http://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp

**Comment by atian25** [comment]
yes, had read it.
but either the device is root, or connect with usb and adb.exe first

**Comment by sidorares** [comment]
there are lots of "adb over wireles without root" apps in google play, I'm sure its doable without usb connection and rooting the device

**Comment by atian25** [comment]
thanks,  dig later.

**Comment by atian25** [comment]
hi @sidorares , sorry, after search in google play, found the `ADB wireless(no-root)`, but it is still need to connect via usb first.

**Comment by sidorares** [comment]
I'll have access to relatively new android phone later today and try to help
